- alias: Wake-up light alarm with sunrise effect
  initial_state: true
  use_blueprint:
    path: sbyx/wake-up-light-with-sunrise-effect1.yaml
    input:
      light_entity: light.yeelight_ceiling3_0x0000000007d1efa6
      check_entity: sensor.lumi_gateway_v3_illuminance
      manual_time: 7:00:00
      sunrise_duration: 35
