# ----- Свет в спальне ----- #

# ----- Включение выключение света по одинарному клику ----- #
- alias: Bedroom Switch Click Light On
  initial_state: true
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.wall_switch_158d000355fbed
        click_type: single
  condition:
    - condition: state
      entity_id: light.yeelight_ceiling3_0x0000000007d1efa6
      state: 'off'
  action:
    - service: light.turn_on
      entity_id: light.yeelight_ceiling3_0x0000000007d1efa6




# ----- Выключение света по одинарному клику ----- #
- alias: Bedroom Switch Click Light Off
  initial_state: true
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.wall_switch_158d000355fbed
        click_type: single
  condition:
    - condition: state
      entity_id: light.yeelight_ceiling3_0x0000000007d1efa6
      state: 'on'
  action:
    - service: light.turn_off
      entity_id:
        - light.yeelight_ceiling3_0x0000000007d1efa6

# ----- Включение 25% яркости по двойному клику ----- #
- alias: Bedroom Switch Doble Click Light_25
  initial_state: true
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.wall_switch_158d000355fbed
        click_type: double
  action:
    - service: light.turn_on
      entity_id:
        - light.yeelight_ceiling3_0x0000000007d1efa6
      data_template:
        brightness_pct: 25
        kelvin: 3900

# ----- Включение 4500К по длинному нажатию ----- #
- alias: Bedroom Switch Long Click Light Max
  initial_state: true
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.wall_switch_158d000355fbed
        click_type: long
  action:
    - service: light.turn_on
      entity_id:
        - light.yeelight_ceiling3_0x0000000007d1efa6
      data_template:
        brightness_pct: 100
        kelvin: 4500

        
# Сценарий Рассвет за 30 минут до будильника в рабочий день
- id: '0105'
  alias: Bedroom_light_workday_sunrise
  initial_state: true
  trigger:
    platform: time
    at: '06:30'
  condition:
    - condition: state  
      entity_id: binary_sensor.amazfit_gtr_lite
      state: 'on'
    - condition: state
      entity_id: binary_sensor.workday_sensor
      state: 'on' 
    - condition: numeric_state
      entity_id: sensor.0x54ef4410000eca07_illuminance_lux
      below: 200
    - condition: state
      entity_id: light.yeelight_ceiling3_0x0000000007d1efa6
      state: 'off'
  action:
    - service: light.turn_on
      data:
        brightness_pct: 40
        color_temp: 3400
        transition: 900
      target:
        entity_id: light.yeelight_ceiling3_0x7d1efa6_nightlight
    - delay: 00:15:30
    - service: light.turn_on
      data:
        brightness_pct: 100
        color_temp: 6500
        transition: 900
      target:
        entity_id: light.yeelight_ceiling3_0x0000000007d1efa6
        

# Если никого нет дома в 8 утра в рабочий день
- alias: Off Bedroom light 8_AM 
  initial_state: true
  trigger:
    platform: time
    at: '08:10'
  condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  - condition: state
    entity_id: binary_sensor.amazfit_gtr_lite
    state: 'off'
  - condition: state
    entity_id: binary_sensor.0x00158d0003cc2d64_occupancy
    state: 'off'
    for:
      minutes: 10
  - condition: state
    entity_id: binary_sensor.0x00158d000421a109_occupancy
    state: 'off'
    for:
      minutes: 10
  - condition: state
    entity_id: binary_sensor.dvizhenie_na_kukhne_occupancy
    state: 'off'
    for:
      minutes: 10
  - condition: state
    entity_id: binary_sensor.motion_sensor_158d0003021440
    state: 'off'
    for:
      minutes: 10
  - condition: state
    entity_id: binary_sensor.motion_sensor_158d0003d12974
    state: 'off'
    for:
      minutes: 10
  - condition: state
    entity_id: binary_sensor.0x00158d0003cc2d64_occupancy
    state: 'off'
    for:
      minutes: 10
  - condition: state
    entity_id: binary_sensor.0x00158d0007274a75_occupancy
    state: 'off'
    for:
      minutes: 10      
  - condition: state
    entity_id: light.yeelight_ceiling3_0x0000000007d1efa6
    state: 'on'      
  action:
    - service: light.turn_off
      entity_id: light.yeelight_ceiling3_0x0000000007d1efa6
      
