# ----- Свет в спальне ----- #

# ----- Включение выключение света по одинарному клику ----- #
- alias: Bedroom Switch Click Light On
  initial_state: true
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.wall_switch_158d000355fbed
        click_type: single
  condition:
    - condition: state
      entity_id: light.yeelight_ceiling3_0x0000000007d1efa6
      state: 'off'
  action:
    - service: light.turn_on
      entity_id: light.yeelight_ceiling3_0x0000000007d1efa6




# ----- Выключение света по одинарному клику ----- #
- alias: Bedroom Switch Click Light Off
  initial_state: true
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.wall_switch_158d000355fbed
        click_type: single
  condition:
    - condition: state
      entity_id: light.yeelight_ceiling3_0x0000000007d1efa6
      state: 'on'
  action:
    - service: light.turn_off
      entity_id:
        - light.yeelight_ceiling3_0x0000000007d1efa6

# ----- Включение 25% яркости по двойному клику ----- #
- alias: Bedroom Switch Doble Click Light_25
  initial_state: true
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.wall_switch_158d000355fbed
        click_type: double
  action:
    - service: light.turn_on
      entity_id:
        - light.yeelight_ceiling3_0x0000000007d1efa6
      data_template:
        brightness_pct: 25
        kelvin: 3900

# ----- Включение 4500К по длинному нажатию ----- #
- alias: Bedroom Switch Long Click Light Max
  initial_state: true
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.wall_switch_158d000355fbed
        click_type: long
  action:
    - service: light.turn_on
      entity_id:
        - light.yeelight_ceiling3_0x0000000007d1efa6
      data_template:
        brightness_pct: 100
        kelvin: 4500