# Включение вентиляции в ванной
- alias: Bathroom Fan Turn ON
  initial_state: true
  trigger:
  - platform: state
    entity_id: switch.0x00158d0006d49f34_l1
    from: 'on'
    to: 'off'
    for:
      minutes: 1
  condition:
  - condition: template
    value_template: >-
      {{ (states('sensor.klimat_v_vannoi_humidity')) > (states('sensor.average_humidity')) }}
  - condition: state
    entity_id: switch.0x00158d0006d49f34_l2
    state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.0x00158d0006d49f34_l2
    - service: timer.start
      entity_id: timer.fan_bathroom_off

#Выключение вентиляции
- alias: Bathroom Fan Turn OFF
  initial_state: true
  trigger:
  - platform: template
    value_template: >-
      {{ (states('sensor.klimat_v_vannoi_humidity')) < (states('sensor.average_humidity')) }}
# берем значение сенсора средняя влажность
  - platform: state
    entity_id: switch.0x00158d0006d49f34_l1
    to: 'on'
  condition:
  - condition: state
    entity_id: switch.0x00158d0006d49f34_l2
    state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.0x00158d0006d49f34_l2


### Выключение вентиляции в случае поломки датчиков (через 90 минут)
- alias: Bathroom Fan Turn OFF Timer On
  initial_state: true
  trigger:
    - platform: event
      event_type: timer.finished
      event_data: 
        entity_id: timer.fan_bathroom_off
  condition:
    - condition: state
      entity_id: switch.0x00158d0006d49f34_l2
      state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.0x00158d0006d49f34_l2
#    - service: notify.telegram
#      data:
#        message: "Внимание. Вентилятор в ванной не был выключен продолжительное время. Время выключения: {{ states('sensor.time') }}"