# Включение вентиляции
- alias: Bathroom Fan Turn ON
  initial_state: true
  trigger:
  - platform: state
    entity_id: switch.relay_lumi_158d0006d49f34_ch0_lumi_158d0006d49f34
    to: 'off'
    for:
      minutes: 1
  condition:
  - condition: numeric_state
    entity_id: sensor.humidity_158d0001dc32b4
    above: 70
  - condition: state
    entity_id: switch.relay_lumi_158d0006d49f34_ch1_lumi_158d0006d49f34
    state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.relay_lumi_158d0006d49f34_ch1_lumi_158d0006d49f34
    - service: timer.start
      entity_id: timer.fan_bathroom_60m_off

#Выключение вентиляции
- alias: Bathroom Fan Turn OFF
  initial_state: true
  trigger:
  - platform: numeric_state
    entity_id: sensor.humidity_lumi_158d0001dc32b4
    below: 65
  condition:
  - condition: state
    entity_id: switch.relay_lumi_158d0006d49f34_ch1_lumi_158d0006d49f34
    state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.relay_lumi_158d0006d49f34_ch1_lumi_158d0006d49f34


### Выключение вентиляции в случае поломки датчиков (через 30 минут)
- alias: Bathroom Fan Turn OFF Timer On
  initial_state: true
  trigger:
    - platform: event
      event_type: timer.finished
      event_data: 
        entity_id: timer.fan_bathroom_60m_off
  condition:
    - condition: state
      entity_id: switch.relay_lumi_158d0006d49f34_ch1_lumi_158d0006d49f34
      state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.relay_lumi_158d0006d49f34_ch1_lumi_158d0006d49f34
    - service: notify.telegram
      data:
        message: "Внимание. Вентилятор в Ванной не был выключен продолжительное время. Время выключения: {{ states('sensor.time') }}"