# Включить свет на кухне
- alias: Kitchen_Turn_ON_light_(motion on)
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0003f1c963
      to: 'on'
  condition:
  - condition: time
    after: '08:00'
    before: '20:00'
  - condition: numeric_state
    entity_id: sensor.lumi_gateway_v3_illuminance
    below: 600
  - condition: state
    entity_id: light.yeelight_ceiling5_0x0000000007f0e59f
    state: 'off'
  action:
    - service: light.turn_on
      entity_id: light.yeelight_ceiling5_0x0000000007f0e59f


### Выключение света на кухне при отсутствии движения в течении 3 минут
- alias: Kitchen_Turn_OFF_light_above_1_min_(no motion)
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0003f1c963
      to: 'off'
      for:
        minutes: 1
  condition:
    - condition: state
      entity_id: light.yeelight_ceiling5_0x0000000007f0e59f
      state: 'on'
  action:
    - service: light.turn_off
      entity_id: light.yeelight_ceiling5_0x0000000007f0e59f


# Включить ночник на кухне
- alias: Kitchen_Turn_ON_light_(motion on)_night
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0003f1c963
      to: 'on'
  condition:
  - condition: time
    after: '20:01'
    before: '07:59'
  - condition: numeric_state
    entity_id: sensor.lumi_gateway_v3_illuminance
    below: 400
  - condition: state
    entity_id: light.lumi_gateway_v3_light
    state: 'off'
  action:
    - service: light.turn_on
      entity_id: light.lumi_gateway_v3_light

### Выключение ночника на кухне при отсутствии движения в течении 3 минут
- alias: Kitchen_Turn_OFF_light_above_1_min_(no motion)_night
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0003f1c963
      to: 'off'
      for:
        minutes: 1
  condition:
    - condition: state
      entity_id: light.lumi_gateway_v3_light
      state: 'on'
  action:
    - service: light.turn_off
      entity_id: light.lumi_gateway_v3_light