# -----Включение света по одинарному клику ----- #
- alias: Kitchen Switch Click Light ON
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.wall_switch_158d0003559ebf
        click_type: single
  condition:
    - condition: state
      entity_id: light.yeelight_ceiling5_0x0000000007f0e59f
      state: 'off'
  action:
    - service: light.turn_on
      entity_id:
        - light.yeelight_ceiling5_0x0000000007f0e59f

# -----Выключение света по одинарному клику ----- #
- alias: Kitchen Switch Click Light Off
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.wall_switch_158d0003559ebf
        click_type: single
  condition:
    - condition: state
      entity_id: light.yeelight_ceiling5_0x0000000007f0e59f
      state: 'on'
  action:
    - service: light.turn_off
      entity_id:
        - light.yeelight_ceiling5_0x0000000007f0e59f

# ----- Включение 25% яркости по двойному клику ----- #
- alias: Kitchen Switch Doble Click Light_25
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.wall_switch_158d0003559ebf
        click_type: double
  action:
    - service: light.turn_on
      entity_id:
        - light.yeelight_ceiling5_0x0000000007f0e59f
      data_template:
        brightness_pct: 25
        kelvin: 3900

# ----- Включение 4500К по длинному нажатию ----- #
- alias: Kitchen Switch Long Click Light Max
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.wall_switch_158d0003559ebf
        click_type: long
  action:
    - service: light.turn_on
      entity_id:
        - light.yeelight_ceiling5_0x0000000007f0e59f
      data_template:
        brightness_pct: 100
        kelvin: 4500





# Включить свет на кухне
- alias: Kitchen_Turn_ON_light_(motion on)
  initial_state: true
  trigger:
    - platform: state
#      entity_id: binary_sensor.motion_sensor_158d0003f1c963
      entity_id:
      - binary_sensor.motion_sensor_158d0003f1c963
      - binary_sensor.motion_sensor_158d0003021440
      to: 'on'
  condition:
  - condition: time
    after: '08:00'
    before: '20:00'
  - condition: numeric_state
    entity_id: sensor.lumi_gateway_v3_illuminance
    below: 500
  - condition: state
    entity_id: light.yeelight_ceiling5_0x0000000007f0e59f
    state: 'off'
  action:
    - service: light.turn_on
      entity_id: light.yeelight_ceiling5_0x0000000007f0e59f


### Выключение света на кухне при отсутствии движения в течении 3 минут
- alias: Kitchen_Turn_OFF_light_above_1_min_(no motion)
  initial_state: true
  trigger:
    - platform: state
#      entity_id: binary_sensor.motion_sensor_158d0003f1c963
      entity_id:
      - binary_sensor.motion_sensor_158d0003f1c963
      - binary_sensor.motion_sensor_158d0003021440
      to: 'off'
      for:
        minutes: 2
  condition:
    - condition: state
      entity_id: light.yeelight_ceiling5_0x0000000007f0e59f
      state: 'on'
  action:
    - service: light.turn_off
      entity_id: light.yeelight_ceiling5_0x0000000007f0e59f


# Включить ночник на кухне
- alias: Kitchen_Turn_ON_light_(motion on)_night
  initial_state: true
  trigger:
    - platform: state
#      entity_id: binary_sensor.motion_sensor_158d0003f1c963
      entity_id:
      - binary_sensor.motion_sensor_158d0003f1c963
      - binary_sensor.motion_sensor_158d0003021440
      to: 'on'
  condition:
  - condition: time
    after: '20:01'
    before: '07:59'
  - condition: numeric_state
    entity_id: sensor.lumi_gateway_v3_illuminance
    below: 400
  - condition: state
    entity_id: light.lumi_gateway_v3_light
    state: 'off'
  action:
    - service: light.turn_on
      entity_id:
        - light.lumi_gateway_v3_light
      data_template:
        brightness: 255
#        rgb_color: 255, 255, 255

### Выключение ночника на кухне при отсутствии движения в течении 3 минут
- alias: Kitchen_Turn_OFF_light_above_1_min_(no motion)_night
  initial_state: true
  trigger:
    - platform: state
#      entity_id: binary_sensor.motion_sensor_158d0003f1c963
      entity_id:
      - binary_sensor.motion_sensor_158d0003f1c963
      - binary_sensor.motion_sensor_158d0003021440
      to: 'off'
      for:
        minutes: 3
  condition:
    - condition: state
      entity_id: light.lumi_gateway_v3_light
      state: 'on'
  action:
    - service: light.turn_off
      entity_id: light.lumi_gateway_v3_light