

# Включить свет в прихожей по движению
- alias: Hall_Turn_ON_light_(motion on)
  initial_state: true
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.0x00158d000421a109_occupancy
    - binary_sensor.motion_sensor_158d0003d12974
    to: 'on'
  condition:
  - condition: time
    after: "07:30"
    before: "20:00"
  - condition: numeric_state
    entity_id: sensor.0x54ef4410000ebe51_illuminance_lux
    below: 6
  - condition: state
    entity_id: switch.svet_v_prikhozhei
    state: "off"
  action:
    - service: switch.turn_on
      entity_id: switch.svet_v_prikhozhei




# Включить ночник в прихожей по движению
- alias: Hall_Turn_ON_light_(motion on)_night
  initial_state: true
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.0x00158d000421a109_occupancy
    - binary_sensor.motion_sensor_158d0003d12974
    to: 'on'
  condition:
  - condition: time
    after: "20:01"
    before: "07:29"
  - condition: state
    entity_id: switch.0x00158d0003c73db6
    state: "off"      
  action:
    - service: switch.turn_on
      entity_id: switch.0x00158d0003c73db6

   

# Выключить свет в прихожей по движению
- alias: Hall_Turn_OFF_light_(motion on)
  initial_state: true
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.0x00158d000421a109_occupancy
    - binary_sensor.motion_sensor_158d0003d12974
    to: 'off'
    for:
      minutes: 2
  condition:
    - condition: state
      entity_id: switch.svet_v_prikhozhei
      state: "on"
  action:
    - service: switch.turn_off
      entity_id: switch.svet_v_prikhozhei

# Выключить ночник в прихожей по движению
- alias: Hall_Turn_OFF_light_(motion on)_night
  initial_state: true
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.0x00158d000421a109_occupancy
    - binary_sensor.motion_sensor_158d0003d12974
    to: 'off'
    for:
      minutes: 1
  condition:
    - condition: state
      entity_id: switch.0x00158d0003c73db6
      state: "on"
  action:
    - service: switch.turn_off
      entity_id: switch.0x00158d0003c73db6

