# -----Включение света по одинарному клику ----- #
- alias: Livingroom Switch Click Light ON
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.wall_switch_158d0002b46857
        click_type: single
  condition:
    - condition: state
      entity_id: light.yeelight_ceiling20_0x000000001588e1a5
      state: 'off'
  action:
    - service: light.turn_on
      entity_id:
        - light.yeelight_ceiling20_0x000000001588e1a5
        
        
# -----Выключение света по одинарному клику ----- #
- alias: Livingroom Switch Click Light ON
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.wall_switch_158d0002b46857
        click_type: single
  condition:
    - condition: state
      entity_id: light.yeelight_ceiling20_0x000000001588e1a5
      state: 'on'
  action:
    - service: light.turn_off
      entity_id:
        - light.yeelight_ceiling20_0x000000001588e1a5

# ----- Включение 25% яркости по двойному клику ----- #
- alias: Livingroom Switch Doble Click Light_25
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.wall_switch_158d0002b46857
        click_type: double
  action:
    - service: light.turn_on
      entity_id:
        - light.yeelight_ceiling20_0x000000001588e1a5
      data_template:
        brightness_pct: 25
        kelvin: 3900

# ----- Включение 4500К по длинному нажатию ----- #
- alias: Livingroom Switch Long Click Light Max
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.wall_switch_158d0002b46857
        click_type: long
  action:
    - service: light.turn_on
      entity_id:
        - light.yeelight_ceiling20_0x000000001588e1a5
      data_template:
        brightness_pct: 100
        kelvin: 4500