# Сообщение об открытии двери
- alias: Door open message
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.0xa4c138367ef577fa_contact
      from: 'off'
      to: 'on'
  condition:
  - condition: state
    entity_id: binary_sensor.0x00158d0003cc2d64_occupancy
# движение в ванной
    state: 'off'
    for:
      minutes: 10
  - condition: state
    entity_id: binary_sensor.0x00158d000421a109_occupancy
# Движение в гостиной 
    state: 'off'
    for:
      minutes: 10
  - condition: state
    entity_id: binary_sensor.dvizhenie_na_kukhne_occupancy
# Движение на кухне 
    state: 'off'
    for:
      minutes: 10
  - condition: state
    entity_id: binary_sensor.motion_sensor_158d0003021440
# Движение в спальне 
    state: 'off'
    for:
      minutes: 10
  - condition: state
    entity_id: binary_sensor.motion_sensor_158d0003d12974
# Движение в прихожей 
    state: 'off'
    for:
      minutes: 10
  - condition: state
    entity_id: binary_sensor.0x00158d0003cc2d64_occupancy
# Движение в ванной 
    state: 'off'
    for:
      minutes: 10
  - condition: state
    entity_id: binary_sensor.0x00158d0007274a75_occupancy
# Движение в туалете 
    state: 'off'
    for:
      minutes: 10
  - condition: state
    entity_id: binary_sensor.amazfit_gtr_lite
# Amazfit GTR Lite 
    state: 'off'
      
  action:
    - service: notify.telegram
      data:
        message: "К нам кто-то пришел в: {{ states('sensor.time') }}"
    - delay: 00:00:05
    - service: telegram_bot.send_photo
      data:
        url: http://192.168.1.101/cam.php        
    - delay: 00:00:04
    - service: telegram_bot.send_photo
      data:
        url: http://192.168.1.101/cam.php    
        
- alias: Door_open_message_10_min 
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.0xa4c138367ef577fa_contact
      from: 'off'
      to: 'on'
      for:
        minutes: 10
  action:
    - service: notify.telegram
      data:
        message: "Внимание. Входная дверь открыта 10 минут!"
        
        
        