- alias: Light - Sunrise
  initial_state: false
  trigger:
  - platform: time
    at: 06:30:00
  condition:
    - condition: time
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
    - condition: numeric_state
      entity_id: sensor.lumi_gateway_v3_illuminance
      below: 500
  action:
  - service: script.sunrise_effect
    data: {}
  - delay: 00:02:00
  - service: timer.start
    entity_id: timer.sunrise_bathroom_90m_off
    
    
- alias: Light - Sunrise -OFF
  initial_state: true
  trigger:
  - platform: event
    event_type: timer.finished
    event_data: 
      entity_id: timer.sunrise_bathroom_90m_off
  condition:
    - condition: state
      entity_id: light.yeelight_ceiling3_0x0000000007d1efa6
      state: 'on'
  action:
  - service: light.turn_off
    entity_id: light.yeelight_ceiling3_0x0000000007d1efa6