# ВКЛ увлажнитель 
- alias: 'humidifier_on'
  initial_state: true
  trigger:
    platform: time
    at: '19:00'
  condition:
  - condition: state
    entity_id: humidifier.zhimi_humidifier_ca1
    state: 'off'
  - condition: state
    entity_id: binary_sensor.zhimi_humidifier_ca1_water_tank
    state: 'on'
  action: 
    - service: humidifier.turn_on
      entity_id: humidifier.zhimi_humidifier_ca1
    - service: humidifier.set_mode
      target:
        entity_id: humidifier.zhimi_humidifier_ca1
      data:
        mode: Auto
      
# Скорость вентилятора ночь 
- alias: 'humidifier_on_Silent'
  initial_state: false
  trigger:
    platform: time
    at: '22:00'
  condition:
  - condition: state
    entity_id: humidifier.zhimi_humidifier_ca1
    state: 'on'
  action: 
    - service: humidifier.set_mode
      target:
        entity_id: humidifier.zhimi_humidifier_ca1
      data:
        mode: Silent
    
      
# ВЫКЛ увлажнитель в рабочий день
- alias: 'humidifier_off_workday'
  initial_state: true
  trigger:
    platform: time
    at: '07:30'
  condition:
  - condition: state
    entity_id: binary_sensor.workday
    state: 'on' 
  - condition: state
    entity_id: humidifier.zhimi_humidifier_ca1
    state: 'on'
  action: 
    - service: humidifier.turn_off
      entity_id: humidifier.zhimi_humidifier_ca1
      
      
# ВЫКЛ увлажнитель в выходной день
- alias: 'humidifier_off_holiday'
  initial_state: true
  trigger:
    platform: time
    at: '10:30'
  condition:
  - condition: state
    entity_id: binary_sensor.workday
    state: 'off' 
  - condition: state
    entity_id: humidifier.zhimi_humidifier_ca1
    state: 'on'
  action: 
    - service: humidifier.turn_off
      entity_id: humidifier.zhimi_humidifier_ca1