- alias: Radio Button Single Click ON/OFF Toggle
  initial_state: true
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d0005cfcaf1
        click_type: single
  action:
    - service: switch.toggle
      entity_id: switch.0x00158d0006d49f34_l1
    - service: timer.start
      entity_id: timer.light_bathroom_30m_off
      
- alias: Radio Button Duble Click ON/OFF Toggle
  initial_state: true
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d0005cfcaf1
        click_type: double
  action:
    - service: switch.toggle
      entity_id: switch.0x00158d0006d49f34_l2
    - service: timer.start
      entity_id: timer.fan_bathroom_off
      

- alias: Radio Button Long Click ON/OFF Toggle
  initial_state: true
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d0005cfcaf1
        click_type: long_click_press
  action:
    - service: switch.toggle
      entity_id: switch.0xa4c138316bba8173
    - service: timer.start
      entity_id: timer.light_toilet_30m_off