- alias: Radiation allert
  initial_state: true
  trigger:
    - platform: numeric_state
      entity_id: sensor.narodmon_radiation
      above: '50'
  condition: []
  action:
    - service: notify.telegram
      data:
        message: "Внимание. Высокий уровень радиации: {{ states('sensor.narodmon_radiation') }} мкР/ч"
