############################## Device Tracker ##################################

# Автоматизации для создания device tracker на основе Binary_sensor
- alias: device_tracker_alex_home
  trigger:
    - platform: state
      entity_id: binary_sensor.amazfit_gtr_lite
    - platform: homeassistant
      event: start
  action:
    - choose:
      - conditions:
        - condition: template
          value_template: "{{ trigger.platform == 'state' }}"
        - condition: template
          value_template: "{{ trigger.to_state.state == 'on' }}"
        sequence:
          - service: device_tracker.see
            data:
              dev_id: alex_amazfit_gtr
              location_name: 'home'
      - conditions:
        - condition: template
          value_template: "{{ trigger.platform == 'homeassistant' }}"
        - condition: state
          entity_id: binary_sensor.amazfit_gtr_lite
          state: 'on'
        sequence:
          - service: device_tracker.see
            data:
              dev_id: alex_amazfit_gtr
              location_name: 'home'
      - conditions:
        - condition: template
          value_template: "{{ trigger.platform == 'state' }}"
        - condition: template
          value_template: "{{ trigger.to_state.state == 'off' }}"
        sequence:
          - service: device_tracker.see
            data:
              dev_id: alex_amazfit_gtr
              location_name: 'not_home'
      - conditions:
        - condition: template
          value_template: "{{ trigger.platform == 'homeassistant' }}"
        - condition: state
          entity_id: binary_sensor.amazfit_gtr_lite
          state: 'off'
        sequence:
          - service: device_tracker.see
            data:
              dev_id: alex_amazfit_gtr
              location_name: 'not_home'