alias: Recorder Purge
initial_state: true
description: ''
trigger:
  - platform: time
    at: '03:21:00'
condition: []
action:
  - service: recorder.purge
    data:
      keep_days: 3
      repack: true
mode: single