homeassistant:
  customize: !include_dir_merge_named includes/customize
  packages: !include_dir_merge_named includes/packages
  
  
  
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/vacuum-card/vacuum-card.js
      type: module
    - url: /hacsfiles/animated-consumption-card/animated-consumption-card.js
      type: module
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js?v=1.12.1
      type: module
    - url: /hacsfiles/mini-humidifier/mini-humidifier-bundle.js?v=2.5.4
      type: module
    - url: /hacsfiles/purifier-card/purifier-card.js
      type: module
    - url: /hacsfiles/lovelace-body-miscale-card/body-miscale-card.js
      type: module
      
# Text to speech
tts:
  - platform: google_translate

sonoff:
  username: !secret username_sonoff
  password: !secret password_sonoff
 
#device_tracker:
#  - platform: padavan_tracker
#    consider_home: 10
#    interval_seconds: 3
#    url: http://192.168.1.1/ # web interface url (don't forget about `/` in the end)
#    username: !secret username_padavan
#    password: !secret password_padavan
    
    

#Telegram
telegram_bot:
  - platform: polling
    api_key: !secret telegram_token
    parse_mode: html
    allowed_chat_ids:
      - !secret telegram_bot_chat_id

notify:
  - name: telegram
    platform: telegram
    chat_id: !secret telegram_bot_chat_id

#Narodmon
narodmon:
  devices:
    - name: "Narodmon"
      sensors:
        - radiation

#Вынос во внешние файлы
group: !include includes/groups.yaml
script: !include includes/scripts.yaml
scene: !include includes/scenes.yaml
recorder: !include includes/recorder.yaml
yeelight: !include includes/yeelight.yaml
timer: !include includes/timer.yaml

#Вынос во внешние папки
binary_sensor: !include_dir_merge_list includes/bi-sensor
sensor: !include_dir_merge_list includes/sensor
automation: !include_dir_merge_list includes/automation

