title: Home Assistant - сервер
views:

  - title: Главная
    icon: mdi:home-assistant
    
    cards:

      - type: vertical-stack
        cards:
        
        - type: markdown
          content: >
             **Текущее состояние**
             
        - type: entities
          show_header_toggle: false
          entities:
            - entity: sensor.time
              name: Текущее время
              icon: mdi:clock-outline
            - entity: sensor.date
              name: Дата
              icon: mdi:calendar-check-outline
              


      - type: vertical-stack
        cards:
        - type: markdown
          content: >
             **Графики** 

        - type: horizontal-stack
          cards:


           - type: gauge
             name: Загрузка CPU
             unit: '%'
             entity: sensor.processor_use_percent
             severity:
                green: 0
                yellow: 60
                red: 85
             
           - type: gauge
             name: Загрузка ОЗУ
             unit: '%'
             entity: sensor.memory_use_percent
             severity:
                green: 0
                yellow: 60
                red: 85
                
        - type: horizontal-stack
          cards:

           - type: gauge
             name: Диск заполнен
             unit: '%'
             entity: sensor.disk_use_percent
             severity:
                green: 0
                yellow: 60
                red: 85    
                
           - type: gauge
             name: Температура CPU
             unit: 'C°'
             entity: sensor.cpu_temperature
             severity:
               green: 0
               yellow: 60
               red: 75

        - type: custom:mini-graph-card
          entities:
            - sensor.maria_db_size
          name: Объем БД
          icon: mdi:database
          line_color: blue
          line_width: 4
          font_size: 75
                
              
  - title: Погода
    icon: mdi:weather-partly-snowy-rainy
    cards:
      - type: vertical-stack
        cards:
        - type: weather-forecast
          entity: weather.home_assistant

        - type: custom:mini-graph-card
          entities:
            - sensor.pressure_mmhg_158d0001dc32b4
          name: Давление
          line_color: blue
          line_width: 4
          font_size: 75

        - type: markdown
          content: >
             **Температура дома**

        - type: entities
          show_header_toggle: false
          entities:
            - entity: sensor.dk1_cloud_d85400_temperature
#            - entity: sensor.dk1_cloud_d85400_humidity
            - entity: sensor.t2_cloud_a0sk00_temperature
#            - entity: sensor.t2_cloud_a0sk00_humidity
            - entity: sensor.klimat_v_vannoi_temperature
#            - entity: sensor.klimat_v_vannoi_humidity



          
  - title: Освещение
    icon: mdi:lightbulb-group
    
          
    cards:
    
      - type: vertical-stack
        cards:
        - type: markdown
          content: >
             **Панель переключателей** 
             
        - type: entities
          show_header_toggle: false
          entities:          
            - entity: light.yeelight_ceiling20_0x000000001588e1a5
              #name: Свет в гостиной
            - entity: light.yeelight_ceiling20_0x000000001588e1a5_ambilight
              #name: Свет в гостиной амбилайт
            - entity: switch.sonoff_100061d346
              #name: Бра в гостиной
            - entity: switch.sonoff_1000f261e0
              #name: Светильник рабочего стола
            - entity: light.yeelight_ceiling3_0x0000000007d1efa6
              #name: Свет в спальне
            - entity: switch.sonoff_100061cac1
              #name: Подсветка в спальне
            - entity: light.yeelight_ceiling5_0x0000000007f0e59f           
              #name: Свет на кухне
            - entity: light.lumi_gateway_v3_light
              #name: Ночник на кухне
            - entity: switch.svet_v_prikhozhei
              #name: Свет в прихожей
            - entity: switch.0x00158d0003c73db6
              #name: Ночник в прихожей
            - entity: switch.0x00158d0006d49f34_l1            
              #name: Свет в ванной
            - entity: switch.0x00158d0006d49f34_l2            
              #name: Вентиляция в ванной
            - entity: switch.sonoff_100001f1ea
              #name: Сбербокс
            - entity: switch.sonoff02
              #name: Удлиннитель в спальне 
            - entity: switch.sonoff_1000d8e906
              #name: Ёлочка
            - entity: light.gyver_lamp_esp_c09fc7
              #name: Лампа Гайвера
            - entity: switch.0xa4c138316bba8173
              #name: Гирлянда на кухне
              
              


      - type: vertical-stack
        cards:
        - type: markdown
          content: >
             **Светильники**    
              
        - type: horizontal-stack
          cards:
            - type: light
              entity: light.yeelight_ceiling20_0x000000001588e1a5
              name: Свет в гостиной
            - type: light
              entity: light.yeelight_ceiling20_0x000000001588e1a5_ambilight
              name: Свет в гостиной амбилайт
            - type: light
              entity: light.yeelight_ceiling3_0x0000000007d1efa6
              name: Свет в спальне
            - type: light
              entity: light.yeelight_ceiling5_0x0000000007f0e59f           
              name: Свет на кухне
 
  - title: Zigbee
    icon: mdi:zigbee
    
    cards:

      - type: vertical-stack
        cards:

        - type: alarm-panel
          entity: alarm_control_panel.lumi_gateway_v3_alarm
          name: Охрана
        
        - type: markdown
          content: >
             **Двери, стулья** 
             
        - type: entities
          show_header_toggle: false
          entities:   
            - entity: binary_sensor.0x00158d0000c2f824_contact
#              name: Входная дверь
            - entity: binary_sensor.0x00158d0003121c47_contact
#              name: Офисное кресло
            - entity: binary_sensor.0x00158d0002e2c1c7_contact
#              табурет
              
        - type: markdown
          content: >
             **Датчик дыма** 
             
        - type: entities
          show_header_toggle: false
          entities:          
            - entity: binary_sensor.smoke_sensor_158d00045f1f2d
              name: Задымление в спальне

            
        - type: markdown
          content: >
             **Уровень заряда** 
             
        - type: entities
          show_header_toggle: false
          entities:
            - entity: sensor.0x00158d0007274a75_battery
#              name: Движение в гостиной
            - entity: sensor.battery_158d0002b46857
#              name: Выключатель в гостиной
            - entity: sensor.0x00158d0000c2f824_battery
#              name: Входная дверь
            - entity: sensor.battery_158d0003559ebf
#              name: Выключатель на кухне
            - entity: sensor.battery_158d000355fbed
#              name: Выключатель в спальне
            - entity: sensor.0x00158d0003cc2d64_battery
#              name: Движение в ванной
#            - entity: sensor.battery_158d0003f1c963
            - entity: sensor.dvizhenie_na_kukhne_battery
#              name: Движение на кухне
            - entity: sensor.battery_158d0003021440
#              name: Движение в на кухне 1.5м
            - entity: sensor.0x00158d000421a109_battery
#              name: Движение в прихожей
            - entity: sensor.battery_158d0003d12974
#              name: Движение в прихожей 1.5м
            - entity: sensor.utechka_na_kukhne_battery
#              name: Утечка на кухне
            - entity: sensor.utechka_v_vannoi_battery
#              name: Утечка в ванной
            - entity: sensor.utechka_v_tualete_battery
#              name: Утечка в туалете
            - entity: sensor.battery_158d00045f1f2d
#              name: Датчик дыма
            - entity: sensor.klimat_v_vannoi_battery
#              name: Температура и влажность в ванной
            - entity: sensor.0x00158d0003121c47_battery
#              name: Офисное кресло
            - entity: sensor.0x00158d0002e2c1c7_battery
#              name: Табурет

              
      - type: vertical-stack
        cards:

        - type: markdown
          content: >
             **Выключатели** 
             
        - type: entities
          show_header_toggle: false
          entities:          
            - entity: switch.0x00158d0006d49f34_l2            
              name: Вентиляция в ванной
            - entity: switch.0x00158d0006d49f34_l1            
              name: Свет в ванной
            - entity: switch.0x00158d0003c73db6
              name: Ночник в прихожей
            - entity: light.lumi_gateway_v3_light
              name: Ночник на кухне
            - entity: switch.0x00158d0003c779c9
              name: Отключение водоснабжения

        - type: markdown
          content: >
             **Освещенность** 
             
        - type: entities
          show_header_toggle: false
          entities:          
            - entity: sensor.lumi_gateway_v3_illuminance
#              name: Шлюз освещенность
            - entity: sensor.illumination_04cf8c8f8501
#              name: Датчик освещенности шлюз
            - entity: sensor.illumination_158d0003021440
#              name: Датчик освещенности на кухне
            - entity: sensor.0x00158d000421a109_illuminance_lux
#              name: Датчик освещенности в прихожей


        - type: markdown
          content: >
             **Движение** 
             
        - type: entities
          show_header_toggle: false
          entities:          
            - entity: binary_sensor.0x00158d0007274a75_occupancy
#              name: Движение в гостиной
            - entity: binary_sensor.0x00158d0003cc2d64_occupancy
#              name: Движение в ванной
            - entity: binary_sensor.dvizhenie_na_kukhne_occupancy
#              name: Движение на кухне
            - entity: binary_sensor.motion_sensor_158d0003021440
#              name: Движение в спальне
            - entity: binary_sensor.0x00158d000421a109_occupancy
#              name: Движение в прихожей
            - entity: binary_sensor.motion_sensor_158d0003d12974
#              name: Движение прихожей 1.5 мин

        - type: markdown
          content: >
             **Датчики протечки** 
             
        - type: entities
          show_header_toggle: false
          entities:          
            - entity: binary_sensor.utechka_na_kukhne_water_leak
#              name: Утечка на кухне
            - entity: binary_sensor.utechka_v_vannoi_water_leak
#              name: Утечка в ванной
            - entity: binary_sensor.utechka_v_tualete_water_leak
#              name: Утечка в туалете
              
              
  - title: Счетчики
    icon: mdi:counter
    
    cards:
    
      - type: vertical-stack
        
        cards:
        - type: markdown
          content: >
             **Электроэнергия**
             
        - type: 'custom:animated-consumption-card'
          entity: sensor.energometr_energy_power
          
        - type: vertical-stack  
          cards:

          - type: entities
            show_header_toggle: false
            entities:          
              - entity: sensor.energometr_energy_total
                name: Показания счетчика
              - entity: sensor.energometr_energy_yesterday
                name: Потребление вчера
              - entity: sensor.energometr_energy_today
                name: Потребление сегодня
              - entity: sensor.energometr_energy_power
                name: Мощность
              - entity: sensor.energometr_energy_apparentpower
                name: Полная мощность
              - entity: sensor.energometr_energy_reactivepower
                name: Реактивная мощность
              - entity: sensor.energometr_energy_factor
                name: Коэффициент мощности
              - entity: sensor.energometr_energy_voltage
                name: Напряжение
              - entity: sensor.energometr_energy_current
                name: Ток
#              - entity: sensor.energometr_energy_totalstarttime
#                name: Дата переключения

      - type: vertical-stack
        cards:

        - type: markdown
          content: >
             **Вода** 
        - type: horizontal-stack
          cards:
          - type: custom:mini-graph-card
            entities:
              - sensor.cold_water
            name: Холодная вода
            line_color: blue
            line_width: 8
            font_size: 150
          - type: custom:mini-graph-card
            entities:
              - sensor.hot_water
            name: Горячая вода
            line_color: '#e74c3c'
            line_width: 8
            font_size: 150 
            
        - type: entities
          show_header_toggle: false
          entities:   
            - entity: sensor.cold_water
              name: Холодная (всего)
            - entity: sensor.hot_water
              name: Горячая (всего)
            - entity: sensor.cold_day
              name: Холодная (день)
            - entity: sensor.hot_day
              name: Горячая (день)  
#            - entity: sensor.waterius_voltage
#              name: Батарея
            #- entity: sensor.waterius_voltage_low
            #  name: Низкий заряд
              

  - title: Увлажнение в спальне
    icon: mdi:water-percent
    cards:
      - type: vertical-stack    
        cards:
        - type: 'custom:mini-humidifier'
          entity: humidifier.zhimi_humidifier_ca1
        - type: custom:mini-graph-card
          entities:
            - sensor.dk1_cloud_d85400_humidity
          name: Влажность в спальне
          line_color: blue
          line_width: 4
          font_size: 150

#        - type: markdown
#          content: >
#             **Влажность в квартире**

        - type: entities
          show_header_toggle: false
          entities:
            - entity: sensor.t2_cloud_a0sk00_humidity
            - entity: sensor.klimat_v_vannoi_humidity


  - title: Уборка помещений
    icon: mdi:broom

    cards:
      - type: 'custom:vacuum-card'
        entity: vacuum.robot_pylesos
        style: |

        stats:
          default:
            - entity_id: sensor.vacuum_cleaner_filter_left
              unit: часов
              subtitle: Фильтр
            - entity_id: sensor.vacuum_cleaner_side_brush_left
              unit: часов
              subtitle: Боковая щетка
            - entity_id: sensor.vacuum_cleaner_main_brush_left
              unit: часов
              subtitle: Основная щетка
            - entity_id: sensor.vacuum_dirty_left
              unit: часов
              subtitle: Датчики
          cleaning:
            - entity_id: sensor.vacuum_cleaner_cleaned_area
              unit: m2
              subtitle: Убрано в кв.м.
            - entity_id: sensor.vacuum_cleaner_cleaning_time
              unit: минут
              subtitle: Время уборки
        shortcuts:
          - name: Уборка в гостиной
            service: script.clean_living_room
            icon: 'mdi:sofa'
          - name: Уборка в спальне
            service: script.clean_badroom_room
            icon: 'mdi:bed'
          - name: Уборка на кухне
            service: script.clean_kitchen_room
            icon: 'mdi:silverware-fork-knife'
          - name: Уборка в прихожей
            service: script.clean_corridor_room
            icon: 'mdi:door-open'
          - name: Коврик в прихожей
            service: script.clean_carpet_corridor
            icon: 'mdi:rug'
        show_status: true
        show_toolbar: true
        show_name: true
        compact_view: false


  - title: Камера
    icon: mdi:camera
    
    cards:
    
      - type: vertical-stack
        
        cards:
        - type: markdown
          content: >
             **Камера**
        - type: iframe
#          url: http://192.168.1.120:8123/local/cam.php
          url: http://192.168.1.100/cam.php
#          url: http://admin:w7cdmtq@192.168.1.50:5914/snapshot.cgi
#          url: http://admin:w7cdmtq@192.168.1.50:5914/videostream.cgi
          aspect_ratio: 75%
          style:
            margin-left: 1000px
            margin-right: 1000px
            heght: 100%
            width: 100%
            transform: none

  - title: Медиа
    icon: mdi:music
    
    cards:
    
      - type: vertical-stack
        
        cards:
          - type: 'custom:mini-media-player'
            entity: media_player.yandex_station
            artwork: cover
            sound_mode: icon
            shortcuts:
              attribute: sound_mode
              buttons:
                - icon: 'mdi:account-voice'
                  id: Произнеси текст
                  type: sound_mode
                - icon: 'mdi:robot'
                  id: Выполни команду
                  type: sound_mode
                - icon: 'mdi:playlist-star'
                  id: включи мою любимую музыку вперемешку
                  type: command
                - icon: 'mdi:playlist-music'
                  id: включи плейлист дня
                  type: command
                - icon: 'mdi:heart'
                  id: лайк
                  type: command
                - icon: 'mdi:heart-off'
                  id: снять лайк
                  type: command
              columns: 6
            hide:
              sound_mode: false
              runtime: false
            tts:
              platform: yandex_station
              
      - type: vertical-stack
        
        cards:
          - type: 'custom:mini-media-player'
            entity: media_player.yandex_station_mini
            artwork: cover
            sound_mode: icon
            shortcuts:
              attribute: sound_mode
              buttons:
                - icon: 'mdi:account-voice'
                  id: Произнеси текст
                  type: sound_mode
                - icon: 'mdi:robot'
                  id: Выполни команду
                  type: sound_mode
                - icon: 'mdi:playlist-star'
                  id: включи мою любимую музыку вперемешку
                  type: command
                - icon: 'mdi:playlist-music'
                  id: включи плейлист дня
                  type: command
                - icon: 'mdi:heart'
                  id: лайк
                  type: command
                - icon: 'mdi:heart-off'
                  id: снять лайк
                  type: command
              columns: 6
            hide:
              sound_mode: false
              runtime: false
            tts:
              platform: yandex_station